config/routes.rb
Rails.application.routes.draw do
  root 'defaults#index'
  
  # Authentication
  devise_for :users, controllers: { registrations: 'registrations'}, skip: [:sessions]

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'users/login', to: 'users#login'
  get 'collaborators', to: 'users#index'
  post 'collaborators', to: 'users#create', as: :new_collaborator

  # Resources
  resources :users
  resources :areas
  resources :categories
  resources :revisions
  resources :asset_revisions, only: [:create, :destroy]

  resources :assets do
    resources :warranties, shallow: true
    resources :technical_details, shallow: true
    resources :network_details, shallow: true
    resources :security_details, shallow: true
    resources :relocations

    resources :identification_codes, only: [:index, :show] do
      member do
        post 'print'
      end
    end

    resources :relocations
    resources :loans do
      post 'toggle', on: :member
    end

    get 'search', on: :collection
  end

  get 'loans', to: 'loans#all', as: :loans
  # get 'tickets', to: 'loans#all', as: :loans

  get 'app', to: 'defaults#app', as: :app
  get 'app/download', to: 'defaults#download', as: :app_download
  get 'help', to: 'defaults#help', as: :help
  get 'status', to: 'defaults#status', as: :status
end

app/models/network_detail.rb
require 'resolv'

class NetworkDetail < ApplicationRecord
  belongs_to :asset, optional: true

  validates :ip, :mask, :gateway, :dns,
            format: {with: Resolv::IPv4::Regex, message: 'Debe ingresar una dirección válida'}
  validates_presence_of :ip, :mask, :gateway, :dns, message: 'Este campo es requerido'
end

app/controllers/network_details_controller.rb
class NetworkDetailsController < ApplicationController
  before_action :find_network_detail, except: [:new, :create]
  before_action :find_asset, except: [:update, :destroy]

  def new
    @network_details = NetworkDetail.new
  end

  def create
    @network_details = NetworkDetail.create(network_details_params)
    @network_details.asset = @asset

    if @network_details.save
      @network_details.asset.has_network_details!
      redirect_to asset_path(@asset), notice: 'Detalles de red guardados correctamente'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @network_details.update(network_details_params)
      redirect_to asset_url(@network_details.asset_id), notice: 'Detalles de red actualizados correctamente'
    else
      render :edit
    end
  end

  def destroy
    @network_details.asset.has_network_details!
    @network_details.destroy
    redirect_to asset_path(@network_details.asset), notice: 'Detalles de red borrados correctamente'
  end

  private
  def network_details_params
    params.required(:network_detail).permit(:ip, :mask, :gateway, :dns)
  end

  def find_network_detail
    @network_details = NetworkDetail.find(params[:id])
  end

  def find_asset
    @asset = Asset.find(params[:asset_id])
  end

end

app/views/network_details/edit.html.erb
<% title 'Editar detalles de red' %>
<div class="row">
  <div class="page-header">
    <h1>Editar detalles de red</h1>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 center-block">
    <%= render 'assets/partials/card', asset: @network_details.asset %>
    <%= simple_form_for @network_details do |f| %>
        <%= render 'network_details/forms/fields', f: f %>
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/network_details/new.html.erb
<% title 'Agregar detalles de red' %>
<div class="row">
  <div class="page-header">
    <h1>Agregar detalles de red</h1>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 center-block">
    <%= render 'assets/partials/card', asset: @asset %>
    <%= simple_form_for @network_details, url: asset_network_details_path(@asset) do |f| %>
      <%= render 'network_details/forms/fields', f: f %>
      <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>