config/routes.rb
Rails.application.routes.draw do
  root 'defaults#index'
  
  # Authentication
  devise_for :users, controllers: { registrations: 'registrations'}, skip: [:sessions]

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'users/login', to: 'users#login'
  get 'collaborators', to: 'users#index'
  post 'collaborators', to: 'users#create', as: :new_collaborator

  # Resources
  resources :users
  resources :areas
  resources :categories
  resources :revisions
  resources :asset_revisions, only: [:create, :destroy]

  resources :assets do
    resources :warranties, shallow: true
    resources :technical_details, shallow: true
    resources :network_details, shallow: true
    resources :security_details, shallow: true
    resources :relocations

    resources :identification_codes, only: [:index, :show] do
      member do
        post 'print'
      end
    end

    resources :relocations
    resources :loans do
      post 'toggle', on: :member
    end

    get 'search', on: :collection
  end

  get 'loans', to: 'loans#all', as: :loans
  # get 'tickets', to: 'loans#all', as: :loans

  get 'app', to: 'defaults#app', as: :app
  get 'app/download', to: 'defaults#download', as: :app_download
  get 'help', to: 'defaults#help', as: :help
  get 'status', to: 'defaults#status', as: :status
end

app/models/technical_detail.rb
class TechnicalDetail < ApplicationRecord
  belongs_to :asset, optional: true

  validates_presence_of :cpu, :ram, :hdd, :os, message: 'Este campo es requerido'

  def hdd_to_nice
    if hdd / 1000 >= 1
      tbs = hdd / 1000
      tbs.to_s + ' TB'
    else
      hdd.to_s + ' GB'
    end
  end
end

app/controllers/technical_details_controller.rb
class TechnicalDetailsController < ApplicationController
  before_action :find_technical_detail, except: [:new, :create]
  before_action :find_asset, except: [:update, :destroy]

  def new
    @technical_detail = TechnicalDetail.new
  end

  def create
    @technical_detail = TechnicalDetail.create(technical_details_params)
    @technical_detail.asset = @asset

    if @technical_detail.save
      @technical_detail.asset.has_tech_details!
      redirect_to asset_path(@asset), notice: 'Especificaciones técnicas guardadas correctamente'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @technical_detail.update(technical_details_params)
      redirect_to asset_url(@technical_detail.asset_id), notice: 'Especificaciones técnicas actualizadas correctamente'
    else
      render :edit
    end
  end

  def destroy
    @technical_detail.asset.has_tech_details!
    @technical_detail.destroy
    redirect_to asset_path(@technical_detail.asset), notice: 'Especificaciones técnicas borradas correctamente'
  end

  private
  def technical_details_params
    params.required(:technical_detail).permit(:cpu, :ram, :hdd, :os, :other, :asset_id)
  end

  def find_technical_detail
    @technical_detail = TechnicalDetail.find(params[:id])
  end

  def find_asset
    @asset = Asset.find(params[:asset_id])
  end
end

app/views/technical_details/edit.html.erb
<% title 'Editar detalles técnicos' %>
<div class="row">
  <div class="page-header">
    <h1>Editar detalles técnicos</h1>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 center-block">
    <%= render 'assets/partials/card', asset: @technical_detail.asset %>
    <%= simple_form_for @technical_detail do |f| %>
      <%= render 'technical_details/forms/fields', f: f %>
      <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/technical_details/new.html.erb
<% title 'Agregar detalles técnicos' %>
<div class="row">
  <div class="page-header">
    <h1>Agregar detalles técnicos</h1>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 center-block">
    <%= render 'assets/partials/card', asset: @asset %>
    <%= simple_form_for @technical_detail, url: asset_technical_details_path(@asset) do |f| %>
      <%= render 'technical_details/forms/fields', f: f %>
      <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>