config/routes.rb
Rails.application.routes.draw do
  root 'defaults#index'
  
  # Authentication
  devise_for :users, controllers: { registrations: 'registrations'}, skip: [:sessions]

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'users/login', to: 'users#login'
  get 'collaborators', to: 'users#index'
  post 'collaborators', to: 'users#create', as: :new_collaborator

  # Resources
  resources :users
  resources :areas
  resources :categories
  resources :revisions
  resources :asset_revisions, only: [:create, :destroy]

  resources :assets do
    resources :warranties, shallow: true
    resources :technical_details, shallow: true
    resources :network_details, shallow: true
    resources :security_details, shallow: true
    resources :relocations

    resources :identification_codes, only: [:index, :show] do
      member do
        post 'print'
      end
    end

    resources :relocations
    resources :loans do
      post 'toggle', on: :member
    end

    get 'search', on: :collection
  end

  get 'loans', to: 'loans#all', as: :loans
  # get 'tickets', to: 'loans#all', as: :loans

  get 'app', to: 'defaults#app', as: :app
  get 'app/download', to: 'defaults#download', as: :app_download
  get 'help', to: 'defaults#help', as: :help
  get 'status', to: 'defaults#status', as: :status
end

app/models/revision.rb
class Revision < ApplicationRecord
  has_many :asset_revisions
  has_many :assets, through: :asset_revisions

  validates_presence_of :name
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  acts_as_token_authentication_handler_for User
  before_action :find_revision, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }

  def index
    respond_to do |format|
      format.html { @revisions = Revision.all }
      format.json { @revisions = Revision.where(open: true) }
    end
  end

  def show
  end

  def new
    @revision = Revision.new
  end

  def edit
  end

  def create
    @revision = Revision.new(revision_params)

    respond_to do |format|
      if @revision.save
        format.html { redirect_to @revision, notice: 'Revision creada satisfactoriamente' }
        format.json { render :show, status: :created, location: @revision }
      else
        format.html { render :new }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @revision.update(revision_params)
        format.html { redirect_to @revision, notice: 'Revision actualizada correctamente' }
        format.json { render :show, status: :ok, location: @revision }
      else
        format.html { render :edit }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @revision.destroy
    respond_to do |format|
      format.html { redirect_to revisions_url, notice: 'Revision fue borrada correctamente' }
      format.json { head :no_content }
    end
  end

  private

    def find_revision
      @revision = Revision.find(params[:id])
    end

    def revision_params
      params.require(:revision).permit(:name, :description, :open)
    end
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/revisions/_asset_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>No.</th>
      <th>No. placa</th>
      <th>Area</th>
      <th>Tipo</th>
      <th>Accion</th>
    </tr>
  </thead>
  <tbody class="list">
    <% @revision.asset_revisions.each do |rev| %>
      <% asset = rev.asset %>
      <tr>
        <td><%= asset.id %></td>
        <td><%= link_to asset.plate_number? ? asset.plate_number : 'N/A', asset_path(asset) %></td>
        <td><%= link_to asset.area.name, area_path(asset.area) %></td>
        <td>
          <span class="type label label-<%= asset.type.include?('Un') ? 'default' : 'info' %>">
            <%= asset.type_to_h.capitalize %>
          </span>
        </td>
        <td>
          <% if @revision.open? %>
            <%= link_to 'Eliminar', asset_revision_path(rev),
                         method: :delete,
                         data: { confirm: '¿Está seguro que desea borrar el activo de la revision?' } %>
          <% else %>
            <p>Revision cerrada</p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @revision.asset_revisions.empty? %>
  <p class="text-center">
    No existen activos registrados para esta revision
  </p>
<% end %>

app/views/revisions/_form.html.erb
<%= simple_form_for(@revision) do |f| %>
  <%= f.input :name, label: 'Nombre' %>
  <%= f.input :description, label: 'Descripción' %>
  <div class="clearfix">
    <strong>Estado</strong>
    <span class="float-right">
      <%= f.input_field :open, label: 'Estado', class: 'toggle', data: { toggle: 'toggle', on: 'Abierta', off: 'Cerrada' } %>
    </span>
  </div>
  <%= f.button :submit, 'Guardar', class: 'btn-primary' %>
<% end %>

app/views/revisions/edit.html.erb
<% title 'Editar revision' %>
<div class="row">
 <div class="page-header">
   <h1>Editar <%= @revision.name.capitalize %></h1>
 </div>

 <div class="col-md-8 col-md-offset-2">
  <%= render 'form' %>
 </div>
</div>

app/views/revisions/index.html.erb
<div class="row">
  <div class="page-header">
    <div class="pull-right">
      <div class="form-inline">
        <%= link_to new_revision_path, class: 'btn btn-primary btn-sm' do %>
            <%= fa_icon 'plus' %> Nueva revision
        <% end %>
        <input class="form-control input-sm" placeholder="Buscar revision" id="revision-list-search">
      </div>
    </div>
    <h1>Revisiones de activos</h1>
  </div>

  <div class="col-md-12" id="revisions-list">
    <div class="alert alert-info alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= fa_icon 'info' %> Recuerde que para agregar activos a revisiones debe utilizar la aplicacion movil
    </div>

    <% if @revisions.empty? %>
      <div class="text-center">
        <p>No existen revisiones, puede crear una nueva <%= link_to 'aquí', new_revision_path %></p>
      </div>
    <% end %>

    <ul class="list-unstyled list">
      <% @revisions.each do |revision| %>
        <li>
          <div class="col-md-4 col-equal">
            <div class="panel panel-default panel-equal">
              <div class="panel-body">
                <%= link_to revision_path(revision) do %>
                    <h4 class="name"><%= revision.name.capitalize %></h4>
                <% end %>
                <div class="col-xs-12 text-small">
                  <ul class="list-inline">
                    <li>
                      <%= fa_icon revision.open ? 'unlock' : 'lock' %>
                      <strong>Abierta:</strong> <%= revision.open ? 'Si' : 'No' %>
                    </li>
                    <li>
                      <%= fa_icon 'list' %>
                      <strong>Ultima edicion:</strong> <%= revision.updated_at.strftime("%d-%m-%Y") %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/revisions/new.html.erb
<h1>New Revision</h1>

<%= render 'form', revision: @revision %>

<%= link_to 'Back', revisions_path %>

app/views/revisions/show.html.erb
<div class="row">
  <div class="page-header">
    <div class="pull-right">
      <%= link_to edit_revision_path(@revision), class: 'btn btn-primary btn-sm' do %>
          <%= fa_icon 'pencil' %> Editar revision
      <% end %>
    </div>
    <h1><%= @revision.name %></h1>
  </div>

  <div class="col-md-12 text-small">
    <ul class="list-inline">
      <li>
        <%= fa_icon @revision.open ? 'unlock' : 'lock' %>
        <strong>Abierta:</strong> <%= @revision.open ? 'Si' : 'No' %>
      </li>
      <li>
        <%= fa_icon 'calendar' %>
        <strong>Creada:</strong> <%= time_ago_in_words(@revision.created_at) %>
      </li>
      <li>
        <%= fa_icon 'list' %>
        <strong>Ultima edicion:</strong> <%= time_ago_in_words(@revision.updated_at) %>
      </li>
    </ul>
  </div>

  <div class="col-md-12 description">
    <p class="text-justify"><%= @revision.description || 'No hay descripcion disponible' %></p>
  </div>

  <div class="col-md-12">
    <div class="page-header">
      <h3>Activos registrados <small>(<%= @revision.asset_revisions.count %>)</small></h3>
    </div>
    <div class="col-md-8 col-md-offset-2" id="asset-list">
      <%= render "asset_list" %>
    </div>
  </div>
</div>