config/routes.rb
Rails.application.routes.draw do
  root 'defaults#index'
  
  # Authentication
  devise_for :users, controllers: { registrations: 'registrations'}, skip: [:sessions]

  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'users/login', to: 'users#login'
  get 'collaborators', to: 'users#index'
  post 'collaborators', to: 'users#create', as: :new_collaborator

  # Resources
  resources :users
  resources :areas
  resources :categories
  resources :revisions
  resources :asset_revisions, only: [:create, :destroy]

  resources :assets do
    resources :warranties, shallow: true
    resources :technical_details, shallow: true
    resources :network_details, shallow: true
    resources :security_details, shallow: true
    resources :relocations

    resources :identification_codes, only: [:index, :show] do
      member do
        post 'print'
      end
    end

    resources :relocations
    resources :loans do
      post 'toggle', on: :member
    end

    get 'search', on: :collection
  end

  get 'loans', to: 'loans#all', as: :loans
  # get 'tickets', to: 'loans#all', as: :loans

  get 'app', to: 'defaults#app', as: :app
  get 'app/download', to: 'defaults#download', as: :app_download
  get 'help', to: 'defaults#help', as: :help
  get 'status', to: 'defaults#status', as: :status
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, except: [:index, :new, :create]

  def index
    @categories = AssetCategory.all

    respond_to do |format|
      format.html
      format.json { render json: @categories }
    end
  end

  def show
  end

  def new
    @category = AssetCategory.new
  end

  def create
    @category = AssetCategory.new(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Categoría creada correctamente'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: 'Categoría actualizada correctamente'
    else
      render :edit
    end
  end

  private
  def category_params
    params.required(:asset_category).permit(:name, :description,
                                            :accepts_warranty_details, :accepts_technical_details,
                                            :accepts_network_details, :accepts_security_details)
  end

  def find_category
    @category = AssetCategory.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= f.input :name, label: 'Nombre' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= f.input :description, label: 'Descripción' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default ">
      <div class="panel-body">
        <div class="clearfix">
          <strong>¿Acepta detalles de garantía?</strong>
          <p>Marque la opción sólo si los activos que vayan a tener esta categoría tienen garantía</p>
          <span class="float-right">
              <%= f.input_field :accepts_warranty_details, class: 'toggle', data: {toggle: 'toggle', on: 'Sí', off: 'No'} %>
            </span>
        </div>
        <hr/>
        <div class="clearfix">
          <strong>¿Acepta detalles técnicos?</strong>
          <p>Establece si los activos que posean esta categoría son aptops para tener detalles como
            cantidad de memoría RAM, nombre del sistema operativo, entre otros.</p>
          <span class="float-right">
              <%= f.input_field :accepts_technical_details, class: 'toggle', data: {toggle: 'toggle', on: 'Sí', off: 'No'} %>
            </span>
        </div>
        <hr/>
        <div class="clearfix">
          <strong>¿Acepta detalles de red?</strong>
          <p>Establece si los activos que posean esta categoría son aptops para tener detalles como
            dirección IP o puerta de enlace. Tome en cuenta que estos detalles son válidos para aquellos
            equipos que se conecten a la red.</p>
          <span class="float-right">
              <%= f.input_field :accepts_network_details, class: 'toggle', data: {toggle: 'toggle', on: 'Sí', off: 'No'} %>
            </span>
        </div>
        <hr/>
        <div class="clearfix">
          <strong>¿Acepta detalles de seguridad?</strong>
          <p>Establece si los activos que posean esta categoría son aptops para tener detalles como
            nombre de usuario y contraseña.</p>
          <span class="float-right">
              <%= f.input_field :accepts_security_details, class: 'toggle', data: {toggle: 'toggle', on: 'Sí', off: 'No'} %>
            </span>
        </div>
      </div>
    </div>
  </div>
</div>
<%= f.submit 'Guardar', class: 'btn btn-primary' %>

app/views/categories/edit.html.erb
<% title "Editar categoría: #{@category.name.downcase}" %>
<div class="row">
  <div class="page-header">
    <h1>Editar categoría</h1>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 center-block">
    <%= simple_form_for @category, url: category_url(@category.id) do |f| %>
      <%= render 'categories/form', f: f %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% title 'Categorías' %>
<div class="row">
  <div class="page-header">
    <div class="pull-right">
      <div class="form-inline">
        <%= link_to new_category_path, class: 'btn btn-primary btn-sm' do %>
            <%= fa_icon 'plus' %> Nueva categoría
        <% end %>
        <input class="form-control input-sm" placeholder="Buscar categoria" id="category-list-search">
      </div>
    </div>
    <h1>Categorías</h1>
  </div>

  <div class="col-md-12" id="category-list">
    <% if @categories.empty? %>
        <div class="text-center">
          <p>No existen categorias registradas, puede crear una nueva
            categoria <%= link_to 'aquí', new_category_path %></p>
        </div>
    <% end %>
    <ul class="list-unstyled list">
      <% @categories.each do |category| %>
        <li>
          <div class="col-md-3 col-equal">
            <div class="panel panel-default panel-equal">
              <div class="panel-body">
                <%= link_to category_path(category) do %>
                    <h4 class="name" title="<%= category.name.capitalize %>">
                      <%= truncate(category.name.capitalize, length: 14, separator: '...') %>
                    </h4>
                <% end %>
                <p><%= truncate(category.description, length: 30, separator: '...') %></p>
                <%= fa_icon 'cubes fw', text: category.assets.count, title: 'Activos' %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/categories/new.html.erb
<% title 'Nueva categoría' %>
<div class="row">
  <div class="page-header">
    <h1>Nueva categoría</h1>
  </div>
  <div class="col-xs-12 col-sm-10 col-md-8 center-block">
    <%= simple_form_for @category, url: categories_path do |f| %>
        <%= render 'categories/form', f: f %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<% title "Categoría #{@category.name.downcase}" %>
<div class="row">
  <div class="page-header">
    <div class="pull-right">
      <%= link_to fa_icon('edit') + ' Editar', edit_category_url(@category.id), class: 'btn btn-sm btn-primary' %>
    </div>
    <h1><%= @category.name %>
      <small><%= "##{@category.id}" %></small>
    </h1>
  </div>
  <div class="col-xs-12 col-sm-9 category-details">
    <div class="description">
      <div class="title h4"><strong>Descripción</strong></div>
      <p><%= @category.description %></p>
    </div>
    <div class="accepts">
      <div class="title h4"><strong>Detalles aceptados</strong></div>
      <p>Esta categoría <strong>
        <% unless @category.accepts_warranty_details %>no
        <% end %> permite</strong> detalles de garantía</p>
      <p>Esta categoría <strong>
        <% unless @category.accepts_technical_details %>no
        <% end %> permite</strong> detalles técnicos</p>
      <p>Esta categoría <strong>
        <% unless @category.accepts_network_details %>no
        <% end %> permite</strong> detalles de red</p>
      <p>Esta categoría <strong>
        <% unless @category.accepts_security_details %>no
        <% end %> permite</strong> detalles de seguridad</p>
    </div>
  </div>
</div>